package quickgui.codegen;

import quickgui.model.Button;
import quickgui.model.CheckBox;
import quickgui.model.ComboBox;
import quickgui.model.GUIElement;
import quickgui.model.GUIVisitor;
import quickgui.model.Label;
import quickgui.model.Layout;
import quickgui.model.LayoutType;
import quickgui.model.Panel;
import quickgui.model.Position;
import quickgui.model.Separator;
import quickgui.model.Slider;
import quickgui.model.TextArea;
import quickgui.model.TextField;
import quickgui.model.Widget;
import quickgui.model.Window;

import java.util.List;

/**
 * Code generator: walks the GUI meta-model and produces a standalone
 * Java Swing source file that, when compiled and run, creates the
 * same GUI defined by the DSL program.
 *
 * This demonstrates the "external DSL → code generation" aspect of
 * model-driven software development: the model (built via the internal DSL)
 * is transformed into executable artefacts in another form.
 */
public class JavaCodeGenerator implements GUIVisitor {

    private final String className;
    private final StringBuilder sb = new StringBuilder();
    private int indent = 2;

    /** Counter for generating unique variable names. */
    private int varCounter = 0;

    /** The variable name of the component most recently generated. */
    private String currentVar;

    public JavaCodeGenerator(String className) {
        this.className = className;
    }

    /**
     * Generate the complete Java source for the given Window model.
     *
     * @param window the Window model root
     * @return a String containing compilable Java source code
     */
    public String generate(Window window) {
        sb.setLength(0);
        varCounter = 0;

        // --- file header ---
        line(0, "import javax.swing.*;");
        line(0, "import java.awt.*;");
        line(0, "");
        line(0, "/**");
        line(0, " * Auto-generated by QuickGUI Code Generator.");
        line(0, " * This file was produced from a QuickGUI DSL model.");
        line(0, " */");
        line(0, "public class " + className + " {");
        line(0, "");
        line(1, "public static void main(String[] args) {");
        line(2, "SwingUtilities.invokeLater(() -> {");

        // --- frame setup ---
        line(3, "JFrame frame = new JFrame(\"" + escape(window.getTitle()) + "\");");
        line(3, "frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);");
        line(3, "frame.setSize(" + window.getWidth() + ", " + window.getHeight() + ");");
        line(3, "frame.setLayout(" + layoutExpr(window.getLayout()) + ");");
        line(3, "");

        // --- children ---
        indent = 3;
        generateChildren("frame.getContentPane()", window.getChildren(),
                          window.getPositions(), window.getLayout());

        line(3, "frame.setLocationRelativeTo(null);");
        line(3, "frame.setVisible(true);");
        line(2, "});");
        line(1, "}");
        line(0, "}");

        return sb.toString();
    }

    // ───────── Visitor methods ─────────

    @Override
    public void visit(Window window) { /* handled in generate() */ }

    @Override
    public void visit(Panel panel) {
        String var = nextVar("panel");

        line(indent, "JPanel " + var + " = new JPanel(" + layoutExpr(panel.getLayout()) + ");");

        if (panel.getBorderTitle() != null) {
            line(indent, var + ".setBorder(BorderFactory.createTitledBorder(");
            line(indent, "    BorderFactory.createEtchedBorder(), \"" + escape(panel.getBorderTitle()) + "\"));");
        }

        int savedIndent = indent;
        generateChildren(var, panel.getChildren(), panel.getPositions(), panel.getLayout());
        indent = savedIndent;

        currentVar = var;
    }

    @Override
    public void visit(Label label) {
        String var = nextVar("label");
        line(indent, "JLabel " + var + " = new JLabel(\"" + escape(label.getText()) + "\");");
        generateTooltip(var, label);
        currentVar = var;
    }

    @Override
    public void visit(Button button) {
        String var = nextVar("button");
        line(indent, "JButton " + var + " = new JButton(\"" + escape(button.getLabel()) + "\");");

        if (button.getAction() != null) {
            line(indent, var + ".addActionListener(e -> System.out.println(\""
                 + escape(button.getLabel()) + " clicked\"));");
        }
        generateTooltip(var, button);
        currentVar = var;
    }

    @Override
    public void visit(TextField textField) {
        String var = nextVar("textField");
        line(indent, "JTextField " + var + " = new JTextField(\""
             + escape(textField.getDefaultText()) + "\", " + textField.getColumns() + ");");
        generateTooltip(var, textField);
        currentVar = var;
    }

    @Override
    public void visit(TextArea textArea) {
        String var = nextVar("textArea");
        line(indent, "JTextArea " + var + " = new JTextArea(\""
             + escape(textArea.getDefaultText()) + "\", "
             + textArea.getRows() + ", " + textArea.getCols() + ");");
        line(indent, var + ".setLineWrap(true);");
        line(indent, var + ".setWrapStyleWord(true);");
        generateTooltip(var, textArea);

        if (textArea.isScrollable()) {
            String scrollVar = nextVar("scroll");
            line(indent, "JScrollPane " + scrollVar + " = new JScrollPane(" + var + ");");
            currentVar = scrollVar;
        } else {
            currentVar = var;
        }
    }

    @Override
    public void visit(CheckBox checkBox) {
        String var = nextVar("checkBox");
        line(indent, "JCheckBox " + var + " = new JCheckBox(\""
             + escape(checkBox.getLabel()) + "\", " + checkBox.isSelected() + ");");
        generateTooltip(var, checkBox);
        currentVar = var;
    }

    @Override
    public void visit(ComboBox comboBox) {
        String var = nextVar("comboBox");
        StringBuilder items = new StringBuilder("new String[]{");
        for (int i = 0; i < comboBox.getItems().size(); i++) {
            if (i > 0) items.append(", ");
            items.append("\"").append(escape(comboBox.getItems().get(i))).append("\"");
        }
        items.append("}");
        line(indent, "JComboBox<String> " + var + " = new JComboBox<>(" + items + ");");
        line(indent, var + ".setSelectedIndex(" + comboBox.getSelectedIndex() + ");");
        generateTooltip(var, comboBox);
        currentVar = var;
    }

    @Override
    public void visit(Slider slider) {
        String var = nextVar("slider");
        line(indent, "JSlider " + var + " = new JSlider("
             + slider.getMin() + ", " + slider.getMax() + ", " + slider.getValue() + ");");
        if (slider.isShowTicks()) {
            line(indent, var + ".setMajorTickSpacing(" + slider.getMajorTickSpacing() + ");");
            line(indent, var + ".setPaintTicks(true);");
            line(indent, var + ".setPaintLabels(true);");
        }
        generateTooltip(var, slider);
        currentVar = var;
    }

    @Override
    public void visit(Separator separator) {
        String var = nextVar("separator");
        String orient = (separator.getOrientation() == Separator.Orientation.HORIZONTAL)
                        ? "SwingConstants.HORIZONTAL" : "SwingConstants.VERTICAL";
        line(indent, "JSeparator " + var + " = new JSeparator(" + orient + ");");
        currentVar = var;
    }

    // ───────── helpers ─────────

    private void generateChildren(String parentVar, List<GUIElement> children,
                                   List<Position> positions, Layout layout) {
        for (int i = 0; i < children.size(); i++) {
            GUIElement child = children.get(i);
            Position   pos   = positions.get(i);

            child.accept(this); // sets currentVar
            String childVar = currentVar;

            if (layout.getType() == LayoutType.BORDER && pos != null) {
                line(indent, parentVar + ".add(" + childVar + ", BorderLayout."
                     + pos.name() + ");");
            } else {
                line(indent, parentVar + ".add(" + childVar + ");");
            }
            line(indent, "");
        }
    }

    private void generateTooltip(String var, Widget widget) {
        if (widget.getTooltip() != null) {
            line(indent, var + ".setToolTipText(\"" + escape(widget.getTooltip()) + "\");");
        }
    }

    private String layoutExpr(Layout spec) {
        switch (spec.getType()) {
            case FLOW:
                return "new FlowLayout(FlowLayout.LEFT, " + spec.getHgap() + ", " + spec.getVgap() + ")";
            case GRID:
                return "new GridLayout(" + spec.getRows() + ", " + spec.getCols()
                       + ", " + spec.getHgap() + ", " + spec.getVgap() + ")";
            case BORDER:
                return "new BorderLayout(" + spec.getHgap() + ", " + spec.getVgap() + ")";
            case VERTICAL:
                return "new GridLayout(0, 1, " + spec.getHgap() + ", " + spec.getVgap() + ")";
            case HORIZONTAL:
                return "new GridLayout(1, 0, " + spec.getHgap() + ", " + spec.getVgap() + ")";
            default:
                return "new FlowLayout()";
        }
    }

    private String nextVar(String prefix) {
        return prefix + (++varCounter);
    }

    private void line(int indentLevel, String code) {
        for (int i = 0; i < indentLevel; i++) sb.append("    ");
        sb.append(code).append("\n");
    }

    private String escape(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n");
    }
}
